// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CineGestionPro.API.Migrations
{
    [DbContext(typeof(CineGestionProAPIContext))]
    [Migration("20261002204504_V03")]
    partial class V03
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CineGestionPro.Modelos.Alquiler", b =>
                {
                    b.Property<int>("id_alquiler")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_alquiler");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_alquiler"));

                    b.Property<decimal>("costo_total")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("costo_total");

                    b.Property<DateTime>("fecha_alquiler")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_alquiler");

                    b.Property<DateTime>("fecha_devolucion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_devolucion");

                    b.Property<int?>("id_usuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.HasKey("id_alquiler");

                    b.HasIndex("id_usuario");

                    b.ToTable("Alquileres");
                });

            modelBuilder.Entity("CineGestionPro.Modelos.Categoria", b =>
                {
                    b.Property<int>("id_categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_categoria"));

                    b.Property<string>("descripcion_categoria")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion_categoria");

                    b.Property<string>("nombre_categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_categoria");

                    b.HasKey("id_categoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("CineGestionPro.Modelos.Contenido", b =>
                {
                    b.Property<int>("id_contenido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_contenido");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_contenido"));

                    b.Property<int>("anio_lanzamiento")
                        .HasColumnType("integer")
                        .HasColumnName("anio_lanzamiento");

                    b.Property<int>("id_categoria")
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria");

                    b.Property<string>("sinopsis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sinopsis");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("titulo");

                    b.HasKey("id_contenido");

                    b.HasIndex("id_categoria");

                    b.ToTable("Contenido");
                });

            modelBuilder.Entity("CineGestionPro.Modelos.DetalleAlquiler", b =>
                {
                    b.Property<int>("id_detalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_detalle"));

                    b.Property<DateTime>("fecha_devolucion_real")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_devolucion_real");

                    b.Property<int>("id_alquiler")
                        .HasColumnType("integer")
                        .HasColumnName("id_alquiler");

                    b.Property<int>("id_ejemplar")
                        .HasColumnType("integer")
                        .HasColumnName("id_ejemplar");

                    b.Property<decimal>("precio_unitario")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_unitario");

                    b.HasKey("id_detalle");

                    b.HasIndex("id_alquiler");

                    b.HasIndex("id_ejemplar");

                    b.ToTable("detalle_alquiler");
                });

            modelBuilder.Entity("CineGestionPro.Modelos.Ejemplar", b =>
                {
                    b.Property<int>("id_ejemplar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_ejemplar");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_ejemplar"));

                    b.Property<string>("codigo_identificacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_identificacion");

                    b.Property<string>("estado_disponibilidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_disponibilidad");

                    b.Property<string>("formato")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("formato");

                    b.Property<int>("id_contenido")
                        .HasColumnType("integer")
                        .HasColumnName("id_contenido");

                    b.HasKey("id_ejemplar");

                    b.HasIndex("id_contenido");

                    b.ToTable("Ejemplares");
                });

            modelBuilder.Entity("CineGestionPro.Modelos.Rol", b =>
                {
                    b.Property<int>("id_rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_rol"));

                    b.Property<string>("nombre_rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_rol");

                    b.HasKey("id_rol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CineGestionPro.Modelos.Usuario", b =>
                {
                    b.Property<int>("id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_usuario"));

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("contrasena")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contrasena");

                    b.Property<string>("correo_electronico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correo");

                    b.Property<DateTime>("fecha_registro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<int>("id_rol")
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("telefono");

                    b.HasKey("id_usuario");

                    b.HasIndex("id_rol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CineGestionPro.Modelos.Alquiler", b =>
                {
                    b.HasOne("CineGestionPro.Modelos.Usuario", "Usuario")
                        .WithMany("Alquileres")
                        .HasForeignKey("id_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CineGestionPro.Modelos.Contenido", b =>
                {
                    b.HasOne("CineGestionPro.Modelos.Categoria", "Categoria")
                        .WithMany("Contenidos")
                        .HasForeignKey("id_categoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("CineGestionPro.Modelos.DetalleAlquiler", b =>
                {
                    b.HasOne("CineGestionPro.Modelos.Alquiler", "Alquiler")
                        .WithMany("DetalleAlquileres")
                        .HasForeignKey("id_alquiler")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CineGestionPro.Modelos.Ejemplar", "Ejemplar")
                        .WithMany("DetallesAlquiler")
                        .HasForeignKey("id_ejemplar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alquiler");

                    b.Navigation("Ejemplar");
                });

            modelBuilder.Entity("CineGestionPro.Modelos.Ejemplar", b =>
                {
                    b.HasOne("CineGestionPro.Modelos.Contenido", "Contenido")
                        .WithMany("Ejemplares")
                        .HasForeignKey("id_contenido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contenido");
                });

            modelBuilder.Entity("CineGestionPro.Modelos.Usuario", b =>
                {
                    b.HasOne("CineGestionPro.Modelos.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("id_rol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("CineGestionPro.Modelos.Alquiler", b =>
                {
                    b.Navigation("DetalleAlquileres");
                });

            modelBuilder.Entity("CineGestionPro.Modelos.Categoria", b =>
                {
                    b.Navigation("Contenidos");
                });

            modelBuilder.Entity("CineGestionPro.Modelos.Contenido", b =>
                {
                    b.Navigation("Ejemplares");
                });

            modelBuilder.Entity("CineGestionPro.Modelos.Ejemplar", b =>
                {
                    b.Navigation("DetallesAlquiler");
                });

            modelBuilder.Entity("CineGestionPro.Modelos.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("CineGestionPro.Modelos.Usuario", b =>
                {
                    b.Navigation("Alquileres");
                });
#pragma warning restore 612, 618
        }
    }
}
